USE BUDGET;
DELETE FROM USBANK_CHECK_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/download.csv"
INTO TABLE USBANK_CHECK_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
SELECT * FROM USBANK_CHECK_INPUT;
--
DELETE FROM CAP_ONE_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/export.csv"
INTO TABLE CAP_ONE_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
--
DELETE FROM CHASE_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/Activity.CSV"
INTO TABLE CHASE_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
SELECT *
FROM CHASE_INPUT;