USE BUDGET;
--
DELETE FROM USBANK_CHECK_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/check.csv"
INTO TABLE USBANK_CHECK_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
--
DELETE FROM USBANK_SAVE_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/save.csv"
INTO TABLE USBANK_SAVE_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
--
DELETE FROM USBANK_BROCK_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/brock.csv"
INTO TABLE USBANK_BROCK_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
--
DELETE FROM USBANK_MEGAN_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/megan.csv"
INTO TABLE USBANK_MEGAN_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
--
DELETE FROM CAP_ONE_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/cap_one.csv"
INTO TABLE CAP_ONE_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
--
DELETE FROM CHASE_INPUT;
COMMIT;
LOAD DATA INFILE "/Applications/MAMP/db/mysql/chase.csv"
INTO TABLE CHASE_INPUT
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
COMMIT;
